/**
 * Type definitions for Chargebee Marketplace applications
 * This file provides TypeScript types for common structures used in marketplace applications
 */

/**
 * Event record structure for Chargebee webhook events
 * This represents the actual structure of Chargebee webhook events
 */
export interface EventRecord {
  /** API version */
  api_version: string;
  /** Event content containing the actual data */
  content: Record<string, any>;
  /** Type of the event (e.g., 'customer_created', 'subscription_created') */
  event_type: string;
  /** Unique identifier for the event */
  id: string;
  /** Object type */
  object: string;
  /** Timestamp when the event occurred */
  occurred_at: number;
  /** Source of the event */
  source: string;
  /** Webhook status */
  webhook_status: string;
  /** Array of webhook configurations */
  webhooks: Array<{
    id: string;
    object: string;
    webhook_status: string;
  }>;
}

/**
 * Handler function signature for event handlers
 */
export type EventHandler = (eventData: EventRecord['content']) => Promise<any>;

// Note: Event types are dynamically generated by Chargebee
// Examples include: 'customer_created', 'subscription_created', 'subscription_renewed', etc. 