/**
 * Type definitions for Chargebee Marketplace applications
 * This file provides TypeScript types for common structures used in marketplace applications
 */

/**
 * Event record structure for Chargebee webhook events
 * This represents the actual structure of Chargebee webhook events
 * Note: Event types are dynamically generated by Chargebee
 * Examples include: 'customer_created', 'subscription_created', 'subscription_renewed', etc. 
 */
export interface EventRecord {
    /** API version */
    api_version: string;
    /** Event content containing the actual data */
    content: Record<string, any>;
    /** Type of the event (e.g., 'customer_created', 'subscription_created') */
    event_type: string;
    /** Unique identifier for the event */
    id: string;
    /** Object type */
    object: string;
    /** Timestamp when the event occurred */
    occurred_at: number;
    /** Source of the event */
    source: string;
    /** Webhook status */
    webhook_status: string;
    /** Array of webhook configurations */
    webhooks: Array<{
      id: string;
      object: string;
      webhook_status: string;
    }>;
}

/**
 * iparam inputs (key-value pairs)
 * Keys are parameter names (strings), values can be string, number, boolean, or string array
 * Example: { "api_key": "abc123", "max_requests": 5, "enable_feature": true, "regions": ["US", "EU"] }
 */
export interface IparamInputs {
    [key: string]: string | number | boolean | string[];
}

/**
 * Single argument passed to every event handler.
 * Use payload.event for the webhook event and payload.iparams for installation parameters.
 */
export interface HandlerPayload {
	/** The webhook event record */
	event: EventRecord;
	/** Installation parameter values */
	iparams: IparamInputs;
}