/**
 * Type definitions for Chargebee Marketplace applications
 * This file provides TypeScript types for common structures used in marketplace applications
 */

/**
 * Event record structure for Chargebee webhook events
 * This represents the actual structure of Chargebee webhook events
 * Note: Event types are dynamically generated by Chargebee
 * Examples include: 'customer_created', 'subscription_created', 'subscription_renewed', etc. 
 */
export interface EventRecord {
    /** API version */
    api_version: string;
    /** Event content containing the actual data */
    content: Record<string, any>;
    /** Type of the event (e.g., 'customer_created', 'subscription_created') */
    event_type: string;
    /** Unique identifier for the event */
    id: string;
    /** Object type */
    object: string;
    /** Timestamp when the event occurred */
    occurred_at: number;
    /** Source of the event */
    source: string;
    /** Webhook status */
    webhook_status: string;
    /** Array of webhook configurations */
    webhooks: Array<{
      id: string;
      object: string;
      webhook_status: string;
    }>;
  }

  /**
 * Argument passed to every event handler.
 *
 * Your handler receives one argument: payload. Use payload.event to read the
 * event (id, event_type, content, etc.). This template has no iparams.
 */
export interface HandlerPayload {
	event: EventRecord;
}

/**
 * Optional return value from a handler function.
 *
 * Return this when the handler wants to signal an application-level error
 * WITHOUT triggering a platform retry (e.g. invalid input, business rule
 * violation). Throwing an exception causes the platform to retry the event;
 * returning a HandlerResult with statusCode >= 400 does not.
 *
 * If the handler returns nothing (or undefined), statusCode defaults to 200.
 */
export interface HandlerResult {
	/**
	 * HTTP status code (100–599). Defaults to 200 if omitted.
	 * Return 4xx to signal a non-retryable application error.
	 */
	statusCode?: number;
	/** Optional response body (e.g. a JSON-encoded error message). */
	body?: string;
}