/**
 * Type definitions for Chargebee Marketplace applications
 * This file provides TypeScript types for common structures used in marketplace applications
 */

/**
 * Event record structure for Chargebee webhook events
 * This represents the actual structure of Chargebee webhook events
 * Note: Event types are dynamically generated by Chargebee
 * Examples include: 'customer_created', 'subscription_created', 'subscription_renewed', etc.
 */
export interface EventRecord {
	/** API version */
	api_version: string;
	/** Event content containing the actual data */
	content: Record<string, any>;
	/** Type of the event (e.g., 'customer_created', 'subscription_created') */
	event_type: string;
	/** Unique identifier for the event */
	id: string;
	/** Object type */
	object: string;
	/** Timestamp when the event occurred */
	occurred_at: number;
	/** Source of the event */
	source: string;
	/** Webhook status */
	webhook_status: string;
	/** Array of webhook configurations */
	webhooks: Array<{
		id: string;
		object: string;
		webhook_status: string;
	}>;
}

/** Union of every value an iparam can hold */
export type IparamValue = string | number | boolean | string[];

/** Parameter values for a single section */
export interface SectionObject {
	[key: string]: IparamValue;
}

/**
 * Installation parameter values keyed by section name.
 * Access: payload.iparams.<section_name>.<param_name>
 * Example: { "advance_invoice_configuration": { "schedule_type": "fixed" } }
 */
export interface IparamInputs {
	[sectionName: string]: SectionObject;
}

/**
 * Single argument passed to every event handler.
 * Use payload.event for the webhook event and payload.iparams.<section>.<param> for installation parameters.
 */
export interface HandlerPayload {
	/** The webhook event record */
	event: EventRecord;
	/** Installation parameter values grouped by section */
	iparams: IparamInputs;
}
